Support for goreleaser 2.0.0
golang-templates/seed pull request #319
Opened 2024-06-05 13:00 UTC by shanilhirani

This PR aims to address the issue with a recent breaking change to go-releaser as described here https://github.com/goreleaser/goreleaser/releases/tag/v2.0.0, and [issue](https://github.com/golang-templates/seed/issues/318) has already been created which this aims to resolve.

2024-06-05 13:52 UTC, pellared commented
@shanilhirani, thank you for contribution.

2024-06-05 13:53 UTC, pellared requested changes
You need to bump goreleaser version here: https://github.com/golang-templates/seed/blob/main/tools/go.mod

2024-06-05 14:09 UTC, pellared commented
You need to run `go mod tidy` in `tools` directory.

2024-06-05 14:34 UTC, shanilhirani commented
Thanks for the suggestions - give us a moment and I'll try to get this cleaned up shortly

2024-06-05 20:26 UTC, pellared commented
Still failing.

2024-06-06 10:29 UTC, shanilhirani commented
> Still failing.

Fixed the issue with CI.

This should be good now - I've run the build workflow in my fork/branch and it reports successful. https://github.com/shanilhirani/seed/actions/runs/9399158404

2024-06-10 08:12 UTC, pellared approved these changes

2024-06-18 09:38 UTC, merged